# Generated by Django 6.0 on 2025-12-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('others', 'Others'), ('life', 'Life'), ('food', 'Food'), ('fashions', 'Fashions'), ('travel', 'Travel'), ('bollywood', 'Bollywood'), ('cricket', 'Cricket'), ('others', 'Others')], default='others', max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(max_length=5000),
        ),
    ]
